<?php

return [
	'fields' => [
		[
			'id' => '4900',
			'name' => 'amount',
			'type' => 'amount',
			'mask' => '',
			'values' => [],
			'validations' => [
				[
					'service_field_validation_id' => '3805',
					'service_field_id' => '4900',
					'type' => 'required',
					'param' => [
						'message' => 'Заполните поле',
					],
				],
				[
					'service_field_validation_id' => '3806',
					'service_field_id' => '4900',
					'type' => 'numerical',
					'param' => [
						'max' => '100000',
						'min' => '5',
						'tooBig' => '',
						'message' => '',
						'tooSmall' => '',
						'allowEmpty' => '1',
						'integerOnly' => '',
						'numberPattern' => '/^\\s*[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?\\s*$/',
						'integerPattern' => '/^\\s*[+-]?\\d+\\s*$/',
					],
				],
			],
			'translate' => [
				'service_id' => '81',
				'service_field_name' => 'amount',
				'value' => 'Сумма',
			],
			'is_need_send' => '1',
		],
		[
			'id' => '4901',
			'name' => 'region',
			'type' => 'select_one',
			'mask' => '',
			'values' => [
				[
					'service_field_value_id' => '2529',
					'service_field_id' => '4901',
					'key' => '1',
					'value' => '1 ГЦТ Астана-телеком',
				],
				[
					'service_field_value_id' => '2530',
					'service_field_id' => '4901',
					'key' => '2',
					'value' => '2 Карагандинская ОДТ',
				],
				[
					'service_field_value_id' => '2531',
					'service_field_id' => '4901',
					'key' => '3',
					'value' => '3 Актюбинская ОДТ',
				],
				[
					'service_field_value_id' => '2532',
					'service_field_id' => '4901',
					'key' => '4',
					'value' => '4 Атырауская ОДТ',
				],
				[
					'service_field_value_id' => '2533',
					'service_field_id' => '4901',
					'key' => '5',
					'value' => '5 Павлодарская ОДТ',
				],
				[
					'service_field_value_id' => '2534',
					'service_field_id' => '4901',
					'key' => '6',
					'value' => '6 Южно-казахстанская ОДТ',
				],
				[
					'service_field_value_id' => '2535',
					'service_field_id' => '4901',
					'key' => '8',
					'value' => '8 Костанайская ОДТ',
				],
				[
					'service_field_value_id' => '2536',
					'service_field_id' => '4901',
					'key' => '9',
					'value' => '9 Северо-казахстанская ОДТ',
				],
				[
					'service_field_value_id' => '2537',
					'service_field_id' => '4901',
					'key' => '10',
					'value' => '10 Акмолинская ОДТ',
				],
				[
					'service_field_value_id' => '2538',
					'service_field_id' => '4901',
					'key' => '11',
					'value' => '11 Мангыстауская ОДТ',
				],
				[
					'service_field_value_id' => '2539',
					'service_field_id' => '4901',
					'key' => '12',
					'value' => '12 Восточно-казахстанская ОДТ',
				],
				[
					'service_field_value_id' => '2540',
					'service_field_id' => '4901',
					'key' => '13',
					'value' => '13 Западно-казахстанская ОДТ',
				],
				[
					'service_field_value_id' => '2541',
					'service_field_id' => '4901',
					'key' => '14',
					'value' => '14 Жамбылская ОДТ',
				],
				[
					'service_field_value_id' => '2542',
					'service_field_id' => '4901',
					'key' => '15',
					'value' => '15 Кызылординская ОДТ',
				],
				[
					'service_field_value_id' => '2543',
					'service_field_id' => '4901',
					'key' => '16',
					'value' => '16 Алматинская ОДТ',
				],
				[
					'service_field_value_id' => '2544',
					'service_field_id' => '4901',
					'key' => '17',
					'value' => '17 ГЦТ Алматы-телеком',
				],
			],
			'validations' => [],
			'translate' => [
				'service_id' => '81',
				'service_field_name' => 'region',
				'value' => 'Регион',
			],
			'is_need_send' => '1',
		],
		[
			'id' => '4902',
			'name' => 'txn_id',
			'type' => 'string',
			'mask' => '',
			'values' => [],
			'validations' => [],
			'translate' => [
				'service_id' => '81',
				'service_field_name' => 'txn_id',
				'value' => 'transaction id',
			],
			'is_need_send' => '',
		],
		[
			'id' => '4903',
			'name' => 'account',
			'type' => 'string',
			'mask' => '',
			'values' => [],
			'validations' => [
				[
					'service_field_validation_id' => '3807',
					'service_field_id' => '4903',
					'type' => 'required',
					'param' => [
						'message' => 'Заполните поле',
					],
				],
				[
					'service_field_validation_id' => '3808',
					'service_field_id' => '4903',
					'type' => 'match',
					'param' => [
						'not' => '',
						'message' => '',
						'pattern' => '/^\\d{1,10}$/',
						'allowEmpty' => '1',
					],
				],
				[
					'service_field_validation_id' => '3809',
					'service_field_id' => '4903',
					'type' => 'length',
					'param' => [
						'is' => '',
						'max' => '10',
						'min' => '1',
						'tooLong' => '',
						'encoding' => '',
						'tooShort' => '',
						'allowEmpty' => '1',
					],
				],
			],
			'translate' => [
				'service_id' => '81',
				'service_field_name' => 'account',
				'value' => 'account',
			],
			'is_need_send' => '1',
		],
	],
	
	'rules' => [
		[
			0 => 'amount',
			1 => 'required',
			'message' => 'Заполните поле',
		],
		[
			0 => 'amount',
			1 => 'number',
			'max' => '100000',
			'min' => '5',
			'numberPattern' => '/^\\s*[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?\\s*$/',
			'integerPattern' => '/^\\s*[+-]?\\d+\\s*$/',
			'skipOnEmpty' => '1',
		],
		[
			0 => 'region',
			1 => 'in',
			'range' => [
				'1',
				'2',
				'3',
				'4',
				'5',
				'6',
				'8',
				'9',
				'10',
				'11',
				'12',
				'13',
				'14',
				'15',
				'16',
				'17',
			],
		],
		[
			0 => 'account',
			1 => 'required',
			'message' => 'Заполните поле',
		],
		[
			0 => 'account',
			1 => 'match',
			'pattern' => '/^\\d{1,10}$/',
			'skipOnEmpty' => '1',
		],
		[
			0 => 'account',
			1 => 'string',
			'max' => '10',
			'min' => '1',
			'skipOnEmpty' => '1',
		],
	],
];
